---
- name: "{{ ct_mysql_task_prefix }} Fail if root password is not defined"
  fail:
    msg: "WARNING! You are required to set mysql root password for this role"
  when: ct_mysql_env_mysql_root_password is not defined

- name: "{{ ct_mysql_task_prefix }} Enable ports"
  include_vars: "mysql_ports.yml"
  when: ct_mysql_enable_ports

- name: "{{ ct_mysql_task_prefix }} Create config and data directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: true
  loop:
    - "{{ ct_mysql_path_config_base }}"
    - "{{ ct_mysql_path_data }}"

- name: "{{ ct_mysql_task_prefix }} Create env file"
  template:
    src: "{{ ct_mysql_template_env }}"
    dest: "{{ ct_mysql_path_config_env }}"
    mode: '0644'

- name: "{{ ct_mysql_task_prefix }} Create container"
  docker_container:
    name: "{{ ct_mysql_ct_name }}"
    image: "{{ ct_mysql_ct_image_full }}"
    env_file: "{{ ct_mysql_path_config_env }}"
    restart_policy: "{{ ct_mysql_ct_restart_policy }}"
    state: "{{ ct_mysql_ct_state }}"
    restart: "{{ ct_mysql_ct_restart }}"
    pull: "{{ ct_mysql_ct_pull }}"
    recreate: "{{ ct_mysql_ct_recreate }}"
    ports: "{{ ct_mysql_ct_ports }}"
    volumes: "{{ ct_mysql_ct_mounts }}"
...
